workflows:
  android-build:
    name: Android APK Build
    instance_type: linux_x2
    scripts:
      - name: Build debug APK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
